{% set name = "pypac" %}
{% set version = "0.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/carsonyl/pypac/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f6eee4f3764568a3c0c401edf60a70485e370dcff4e35d1da503454eb1989e72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.0.0
    - tldextract >=2.2.3
    - dukpy >=0.2.2
    - pyobjc-framework-SystemConfiguration >=3.2.1  # [osx]
    # Keep the package noarch but allow for the osx only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - pypac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carsonyl/pypac
  summary: Proxy auto-config and auto-discovery for Python.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
