{% set name = "pypac" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/carsonyl/pypac/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4f49eb1da024d41969ba6474469d268dd2bacbbe06a3877f6ca89f62687b932c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.0.0
    - tldextract >=2.2.3
    - dukpy >=0.2.2
    - pyobjc-framework-SystemConfiguration >=3.2.1  # [osx]
    # Keep the package noarch but allow for the osx only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - pypac
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/carsonyl/pypac
  summary: Proxy auto-config and auto-discovery for Python.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
